### ISSUE TITLE
Create an MDX Page Graphql path error 

### ISSUE THREAD

**Issue by ErnestTeluk** [jlengstorf/gatsby-intermediate#5]
problem with graphql query path 

path is \\\another and \\\ instead of \another and \

if i clone branch error still exist

**Comment by jlengstorf** [comment]
hi, @ErnestTeluk — could you please say more about the problem you're running into? I'm not sure I understand what code you're referring to

**Comment by ErnestTeluk** [comment]
hi, @jlengstorf 
I have a problem with this line of code 
`path: path.join('/', basePath, parent.relativeDirectory, pageName),`
the problem with this line is that the path to the index.js page should be "/" while graphql throws out "//" so that only 404 is displayed instead of the page.
I fixed this problem by changing the code line above to
path: `${basePath}${pageName}`
but I don't really know if this is the correct approach to solve the problem

**Comment by jlengstorf** [comment]
@ErnestTeluk ah, I see what you mean

your approach is totally valid! another way to do it would be to filter out any empty values, but that's more code to get the same result

**Comment by ErnestTeluk** [comment]
@jlengstorf ok thank you then

**Comment by mbcod3** [comment]
The fix doesnt work. I am also getting path error. The homepage throws 404. Page built shows invalid url /\
